#!/bin/sh

case "$1" in
  start)
        /etc/squid3/dnscheck.py -f
        line="10 * * * * /etc/squid3/dnscheck.py"
        (crontab -u root -l; echo "$line" ) | crontab -u root -
        /etc/init.d/squid3 start
        ;;
  stop)

        CRON_TEMP="/tmp/crontmp"
        CRON_NEW="/tmp/cronnew"

        crontab -l >$CRON_TEMP
        awk '$0!~/dnscheck.py/ { print $0 }' $CRON_TEMP >$CRON_NEW
        crontab $CRON_NEW
        /etc/init.d/squid3 stop
        python /etc/squid3/iptables_config.py -d
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac


