#!/bin/sh

case "$1" in
  start)
        /etc/squid3/dnscheck.py
        line="5 * * * * /etc/squid3/dnscheck.py"
        (crontab -u root -l; echo "$line" ) | crontab -u root -
        ;;
  stop)
        /etc/squid3/iptables_clear.sh

        CRON_TEMP="/tmp/crontmp"
        CRON_NEW="/tmp/cronnew"

        crontab -l >$CRON_TEMP
        awk '$0!~/dnscheck.py/ { print $0 }' $CRON_TEMP >$CRON_NEW
        crontab $CRON_NEW
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac


