#!/bin/sh

# Captive portal redirect for ios and android devices

# TODO: We need a script that changes this rule every time the caching dns server updates the entry for e.g. www.apple.com
# TODO: We need redirect rules for windows and android devices as well.

hostlines=()
host_file="/etc/squid3/hosts"
while read -r line
do
  hostlines=("${hostlines[@]}" "${line}")
done < "$host_file"

for host in "${hostlines[@]}"; do
  # Redirects requests to the IPs in the hosts file to a local squid server
  iptables -t nat -A PREROUTING -i bat0 -p tcp -d ${host} --dport 80 -j REDIRECT --to-port 3128
done


